### PR TITLE
Chocolatey deploy fix

### LINKED ISSUE #49: Fix Chocolatey deploy

### PR DESCRIPTION
**Pull request by leoafarias**
closes #49

### CODE REVIEW

**Review by nex3 — COMMENTED** [review]
Thanks for diving into this! It'll be exciting to have this back up and running.

**Comment by leoafarias** [comment]
@nex3 Great question. When you deploy a package to Chocolatey, they run a validation script about some things that could be missing. One of them is this verification file, here is the error that shows up without it.

https://github.com/chocolatey/package-validator/wiki/VerificationFileMissing

You can use this to do checksum, but it is optional. 

TLDR; It's optional to have checksum verification, but the validator does ask for this file.

**Comment by leoafarias** [comment]
@nex3 I believe this needs to be made as a parameter similar to the nuspec file later. I can try to take a look at this at a later time. But I believe you still need a VERIFICATION file even if it's empty.

**Comment by nex3** [comment]
Looking at that link, it seems like this is intended to be a human-readable file that describes how binary files were generated. In our case, the only "binary" is the zip file containing the package's source code. I wonder if it would be easier to just include the source files directly, since the `.nupkg` is already a zip file, and avoid needing a `VERIFICATION` file at all.

**Comment by leoafarias** [comment]
If we able to avoid I think it would be great. Makes things a bit cleaner.

**Comment by leoafarias** [comment]
@nex3 Please let me know if you want me to try to take a look at your suggestion. Wasn't sure what the next steps are.

**Comment by nex3** [comment]
Oh I'm sorry, I should have been more clear. Could you modify the code to copy in each source file directly to the Chocolatey package rather than creating a zip file containing all of them?

**Comment by nex3** [comment]
It looks like the tests are failing...

**Comment by leoafarias** [comment]
@nex3 This seems weird. For me it seems that master is also not passing the tests.

This PR https://github.com/google/dart_cli_pkg/pull/59 shows that it did not pass CI for me. Could this have something to do with it?

**Comment by nex3** [comment]
`master` seems to be [passing on Travis](https://travis-ci.org/github/google/dart_cli_pkg/builds/736201161).

> This PR #59 shows that it did not pass CI for me. Could this have something to do with it?

I'm not sure why it's not showing up on GitHub, but [its build did succeed](https://travis-ci.org/github/google/dart_cli_pkg/builds/735825700).

**Comment by leoafarias** [comment]
hmm ok will dig deeper

**Comment by leoafarias** [comment]
Good news. Silly mistake. Will review the Chocolatey submission process to make sure we are good to go. 

However tests still fail on my local windows machine, but it happens on master also, so will check it out later and open another PR if anything.

**Comment by leoafarias** [comment]
All validations passed on Chocolatey

**Pull request merged**
