### PR TITLE
Update dependencies; Dart SDK version to 3.0.0.

### PR DESCRIPTION
**Pull request by gmpassos**
Many packages that depends on `cli_pkg` can't be updated without update these dependencies and Dart SDK to 3.0.0+.

### CODE REVIEW

**Comment by gmpassos** [comment]
FYI: @nex3

**Comment by nex3** [comment]
Note that it's entirely possible to use `cli_pkg` with packages that require Dart 3 (as Dart Sass does); Dart 3 interprets an upper SDK bound of `< 3.0.0` as allowing 3.x.

**Comment by gmpassos** [comment]
It's not possible to upgrade to `http: ^1.1.0` (Dart 3) if your package is not updated

**Comment by gmpassos** [comment]
Packages that need this update:

https://pub.dev/packages/sass
https://pub.dev/packages/sass_builder


Eventually you will need this update, it's better for other packages to be soon.

Best regards

**Comment by gmpassos** [comment]
> If we're going to _require_ 3.0.0, I'd prefer to go all in and update the codebase to use Dart 3 features. Otherwise, I'd rather just update the dependency versions (and maybe explicitly expand the SDK constraint).

The current update passes `dart analyze` and `dart format`. I currently don't see any code that really needs to be migrated for specific Dart 3 feature, since it's already a null-safe package. The other main features introduced by Dart 3 are records and enhanced switch and if-case statements.

If you need any help migrating it, just ask.

**Comment by gmpassos** [comment]
Note that the only way to use `sass` and `sass_builder` now, for a Dart 3 project with the last version of common packages is to point to a patches fork:

https://github.com/gmpassos/sass_builder

**Comment by nex3** [comment]
I don't think your information is correct. I can locally update the `http` package to 1.0.0 without touching the SDK constraint and it works fine. Similarly, `sass` [currently requires Dart 3](https://github.com/sass/dart-sass/blob/8802c69337c8e7d8d46eddb8668b57ca5daa8942/pubspec.yaml#L10-L11) and is able to install its dependency on `cli_pkg` just fine. All its CI tests are passing.

**Comment by gmpassos** [comment]
Well, I made a simple dart web test here and I'm getting a dependencies resolution error:

```shell
dart create -t web test_sass 
```

pubspec.yaml:
```yaml
name: test_sass
description: Testing sass_builder dependencies.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  path: ^1.8.0
  http: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.2
  build_web_compilers: ^4.0.3
  sass_builder: ^2.2.1
  lints: ^2.1.1

```

```shell
dart pub get
```

```text
Resolving dependencies... (1.3s)
Because sass_builder >=2.1.5 depends on sass ^1.55.0 which depends on http ^0.13.3, sass_builder >=2.1.5 requires http ^0.13.3.
So, because test_sass depends on both http ^1.1.0 and sass_builder ^2.2.1, version solving failed.
```

**Comment by gmpassos** [comment]
Same thing if testing only `cli_pkg`:

```shell
dart create -t web test_cli_pkg
```

pubspec.yaml
```yaml
name: test_cli_pkg
description: Testing cli_pkg dependencies.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  http: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.2
  build_web_compilers: ^4.0.3
  cli_pkg: ^2.4.7
  lints: ^2.1.1

```

```shell
dart pub get
```

```text
Resolving dependencies... (1.1s)
Because cli_pkg 2.4.7 depends on http ^0.13.0 and no versions of cli_pkg match >2.4.7 <3.0.0, cli_pkg ^2.4.7 requires http ^0.13.0.
So, because test_cli_pkg depends on both http ^1.1.0 and cli_pkg ^2.4.7, version solving failed.
```

---

`Dart SDK version: 3.0.6 (stable) (Tue Jul 11 18:49:07 2023 +0000) on "macos_x64"`

**Comment by gmpassos** [comment]
`http: ^1.0.0`
- Min Dart SDK: 3.0

**Comment by nex3** [comment]
Those failures are only caused by incompatible `http` dependencies, not by the SDK constraint. Again, Dart 3 treats an SDK constraint with an upper bound of `<3.0.0` as though its upper bound were `<4.0.0`. We can fix the issue you describe just by expanding the upper bound on the `http` constraint.

**Comment by gmpassos** [comment]
> Those failures are only caused by incompatible `http` dependencies, not by the SDK constraint. 

Yes, I agree.

The point is: do you wish to update the `http` dependency, which requires Dart 3+, without upgrading your own package to require Dart 3? I know that it's possible, but I don't know if this is the ideal.

Best regards.

**Pull request closed without merging**
